export const SEND_PRODUCT_TO_CART = 'SEND_PRODUCT_TO_CART';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const SUBS_QUANTITY ='SUBS_QUANTITY';
export const DELETE_QUANTITY  = 'DELETE_QUANTITY';

